apiVersion: v1
kind: Service
metadata:
  name: a643580-angular-app
  namespace: fse1
spec:
  selector:
    app: a643580-angular-app
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
