apiVersion: v1
kind: Service
metadata:
  name: a643580-fmts-nodejs
  namespace: fse1
spec:
  selector:
    app: a643580-fmts-nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
