apiVersion: apps/v1
kind: Deployment
metadata:
  name: a643580-fmts
  namespace: a643580-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a643580-fmts
  template:
    metadata:
      labels:
        app: a643580-fmts
    spec:
      containers:
      - name: a643580-fmts
        image: leap2024artifact.jfrog.io/docker-local/fmts-backend:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: srvleapdeploy-secret  
