apiVersion: v1
kind: Service
metadata:
  name: a643580-nodejs
  namespace: a643580-ns
spec:
  selector:
    app: a643580-nodejs
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
