apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: a643580-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: leap2024artifact.jfrog.io/docker-local/frontend-trade-marshals:latest
        ports:
        - containerPort: 4200
      imagePullSecrets:
      - name: srvleapdeploy-secret  