apiVersion: v1
kind: Service
metadata:
  name: a643580-fmts
  namespace: a643580-ns
spec:
  type: ClusterIP
  selector:
    app: a643580-fmts
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
