apiVersion: apps/v1
kind: Deployment
metadata:
  name: a643580-spring-app
  namespace: a643580-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a643580-spring-app
  template:
    metadata:
      labels:
        app: a643580-spring-app
    spec:
      containers:
      - name: a643580-spring-app
        image: leap2024artifact.jfrog.io/docker-local/backend-trade-marshals:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:oracle:thin:@a643580-rds.cp8g424og328.ap-south-1.rds.amazonaws.com:1521/ORCL"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "tiger123"
      imagePullSecrets:
      - name: srvleapdeploy-secret
