apiVersion: v1
kind: Service
metadata:
  name: a643580-spring-app
  namespace: a643580-ns
spec:
  selector:
    app: a643580-spring-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
